### ISSUE TITLE
Add terms of use for web3community assets

### ISSUE THREAD

**Issue by vinzvinci** [web3community/brand-assets#4]
Something like this: https://github.com/logos

**Comment by krishguptadev** [comment]
I can write something for this...

**Comment by krishguptadev** [comment]
Dos: 
- [x] Use the web3community logo to link to web3community
- [x] Use the web3community logo in a blog post or news article about web3community
- [x] Do use the right format for your project to ensure proper resolution.
- [x] Do use the [provided logo files](https://github.com/web3community/brand-assets) at their actual size. 
- [x] Do use the logo with “Web3Community” wordmark
- [x] Do use the original colors.

## Donts
- [ ] Use the Web3Community logo for your application’s icon
- [ ] Use/Sell any Web3Community artwork without permission
- [ ] Do not change the original proportions.
- [ ] Do not create your own versions of the [original logo files](https://github.com/web3community/brand-assets).
- [ ] Do not use the logo as text.

**Comment by krishguptadev** [comment]
what do you think @vinzvinci? Once you approve these I could add them to the files you tell me

**Comment by shuklaritvik06** [comment]
> ## Dos:
> 
>     * [x]  Use the web3community logo to link to web3community
> 
>     * [x]  Use the web3community logo in a blog post or news article about web3community
> 
>     * [x]  Do use the right format for your project to ensure proper resolution.
> 
>     * [x]  Do use the [provided logo files](https://github.com/web3community/brand-assets) at their actual size.
> 
>     * [x]  Do use the logo with “Web3Community” wordmark
> 
>     * [x]  Do use the original colors.
> 
> 
> ## Donts
> 
>     * [ ]  Use the Web3Community logo for your application’s icon
> 
>     * [ ]  Use/Sell any Web3Community artwork without permission
> 
>     * [ ]  Do not change the original proportions.
> 
>     * [ ]  Do not create your own versions of the [original logo files](https://github.com/web3community/brand-assets).
> 
>     * [ ]  Do not use the logo as text.

Maybe it'll look good if we use ✅ and ❌ for do's and don't as this is for doc , what you say @vinzvinci

**Comment by krishguptadev** [comment]
Those task lists were intentional. I wanted them to be in these lists from the start 😅

**Comment by vinzvinci** [comment]
Looks good @krishguptadev.

Good idea @shuklaritvik06!

**Comment by krishguptadev** [comment]
So shall I make a pr? Where should these terms be added?

**Comment by vinzvinci** [comment]
Yes, please make PR @krishguptadev. You can add it on the README.md just like this table

![image](https://user-images.githubusercontent.com/73097560/135804173-3713caca-0ea0-477e-b265-5adeff8f8284.png)

**Comment by Panquesito7** [comment]
Awesome work, @krishguptadev! 🚀 I was trying to work on this, but I was busy. 😢

**Comment by shuklaritvik06** [comment]
> Awesome work, @krishguptadev! 🚀 I was trying to work on this, but I was busy. 😢
> 

This review is also a contribution 😄

**Comment by Panquesito7** [comment]
By the way, I have a question: are the logos licensed under CC BY-SA 4.0, or are they not? We should license the branding with that or mention that they have that license. OR change the whole repository's license to CC BY-SA 4.0. @vinzvinci, @KukretiShubham, @mkubdev, @shuklaritvik06, thoughts?

**Comment by krishguptadev** [comment]
I think art work should be licensed under CC BY-SA 4.0

**Comment by mkubdev** [comment]
@Panquesito7 yes, I'll search the license.. you are right

**Comment by krishguptadev** [comment]
@mkubdev I think we should make the license CC BY-NC-ND 4.0. I think this is the piece of text we need to add to the readme:

```html
<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.
```

**Comment by Panquesito7** [comment]
Currently, are we using the MIT license? That's not a good license for branding.
We should change to the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license, IMO. Thoughts?

**Comment by krishguptadev** [comment]
> Currently, are we using the MIT license? That's not a good license for branding.
> We should change to the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license, IMO. Thoughts?
> 

I've already asked for that in the comment above yours, not sure if it has been implemented yet.

**Comment by mkubdev** [comment]
> Currently, are we using the MIT license? That's not a good license for branding. We should change to the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license, IMO. Thoughts?

I think you are right, we should better use CC BY-SA 4.0
