### ISSUE TITLE
I think we should make the license CC BY-NC-ND 4.0

### ISSUE THREAD

**Issue by krishguptadev** [web3community/brand-assets#9]
@mkubdev I think we should make the license CC BY-NC-ND 4.0. I think this is the piece of text we need to add to the readme:

```html
<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.
```

Output:

<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.

_Originally posted by @krishguptadev in https://github.com/web3community/brand-assets/issues/4#issuecomment-934124554_

**Comment by mkubdev** [comment]
@krishguptadev agreed! LGTM 👌

**Comment by vinzvinci** [comment]
Yeah good idea

**Comment by shuklaritvik06** [comment]
+1

**Comment by shuklaritvik06** [comment]
> @krishguptadev agreed! LGTM ok_hand Do you want PR?

Yes :)

**Comment by mkubdev** [comment]
Yup, from [#4 (comment)](https://github.com/web3community/brand-assets/issues/4#issuecomment-961696421), @Panquesito7 suggest  CC BY-SA 4.0 License over MIT

**Comment by krishguptadev** [comment]
> @krishguptadev agreed! LGTM 👌 Do you want PR?

Yeah sure!

**Comment by shuklaritvik06** [comment]
> > @krishguptadev agreed! LGTM ok_hand Do you want PR?
> 
> Yeah sure! Can I be assigned?

Yes :) Assigning you

**Comment by Panquesito7** [comment]
This won't allow anyone to use it for commercial use 😅 if we don't want it to be modified, at least let us use the [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/) license.
